name: CI

on:
  pull_request:
    branches: [ "develop" ]


jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: 체크아웃
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: application.yaml 생성
        run: |
          cd src/main/resources
          echo "${{ secrets.APPLICATION_SECRET_YML }}" > ./application-secret.yml
        working-directory: ${{ env.working-directory }}

      - name: 빌드
        run: |
          chmod +x gradlew
          ./gradlew build -x test
        working-directory: ${{ env.working-directory }}
        shell: bash

      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
          aws-region: ap-northeast-2

      - name: Upload to AWS S3
        run: |
          aws deploy push \
            --application-name drawdraw-codedeploy \
            --ignore-hidden-files \
            --s3-location s3://drawdraw-bucket/$GITHUB_SHA.zip \
            --source .

      - name: Code Deploy
        run: aws deploy create-deployment --application-name drawdraw-codedeploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name samtilee-group
          --s3-location bucket=drawdraw-bucket,bundleType=zip,key=$GITHUB_SHA.zi
